# Generated by Django 5.2.8 on 2025-11-25 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_core_TIENDA_GALLETAS', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='galleta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='galletas/'),
        ),
        migrations.AddField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('PAGADO', 'Pagado'), ('NO_PAGADO', 'No pagado'), ('EN_PROCESO', 'En proceso')], default='EN_PROCESO', max_length=20),
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='admin_core_TIENDA_GALLETAS.carrito')),
                ('galleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_core_TIENDA_GALLETAS.galleta')),
            ],
        ),
    ]
